--Q1. What is the total revenue generated by male vs. female customers?  
SELECT Gender, SUM(`Purchase Amount (USD)`) AS revenue
FROM customer_behavior
GROUP BY Gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT `Customer ID`, Gender, `Purchase Amount (USD)`
FROM customer_behavior
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` > (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM customer_behavior
  );

--Q3. Which are the top 5 products with the highest average review rating?  
SELECT `Item Purchased`, AVG(`Review Rating`) AS avg_rating
FROM customer_behavior
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.  
SELECT `Shipping Type`, AVG(`Purchase Amount (USD)`) AS avg_purchase
FROM customer_behavior
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.  
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer_behavior
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       COUNT(*) AS total_purchases,
       SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases,
       ROUND(SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_percentage
FROM customer_behavior
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on previous purchases
SELECT CASE
           WHEN `Previous Purchases` = 0 THEN 'New'
           WHEN `Previous Purchases` BETWEEN 1 AND 5 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment,
       COUNT(`Customer ID`) AS total_customers
FROM customer_behavior
GROUP BY customer_segment
ORDER BY total_customers DESC;

--Q8. Top 3 most purchased products within each category
SELECT Category, `Item Purchased`, purchase_count
FROM (
    SELECT Category,
           `Item Purchased`,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS rank_in_category
    FROM customer_behavior
    GROUP BY Category, `Item Purchased`
) ranked
WHERE rank_in_category <= 3
ORDER BY Category, purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Previous Purchases`), 2) AS avg_previous_purchases
FROM customer_behavior
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`
ORDER BY total_customers DESC;

--Q10. Revenue contribution of each age group
SELECT CASE
           WHEN Age < 25 THEN 'Young Adult (<25)'
           WHEN Age BETWEEN 25 AND 40 THEN 'Adult (25-40)'
           WHEN Age BETWEEN 41 AND 60 THEN 'Middle-aged (41-60)'
           ELSE 'Senior (60+)'
       END AS age_group,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue,
       ROUND(SUM(`Purchase Amount (USD)`) * 100.0 / 
             (SELECT SUM(`Purchase Amount (USD)`) FROM customer_behavior), 2) AS revenue_percentage
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;






